---
postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: ENV['DATABASE_URL']
  username: exercism
  password: apples

test:
  <<: *postgres
  database: exercism_test

development:
  <<: *postgres
  database: exercism_development
