---
postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DB_HOST"] %>
  username: exercism
  password: apples

test:
  <<: *postgres
  database: exercism_test

development:
  <<: *postgres
  database: <%= ENV['DB_NAME'] %>
